### ISSUE TITLE
'c' just opens popup

### ISSUE THREAD

**Issue by davidpdrsn** [justbur/evil-magit#12]
I'm new to Emacs and I'm having trouble figuring out how to commit. When I press 'c' it just opens a popup with switches and options.

**Comment by justbur** [comment]
You simply type the option you want from the popup. A "standard" commit is
`cc`. To run `git commit --amend` you can do `ca`, for example. Evil-magit
changes the key bindings, but not the way magit functions. For that you can
refer to magit.vc for the manual.

**Comment by davidpdrsn** [comment]
Then emacs says "c is undefined".

**Comment by justbur** [comment]
Can you tell me in steps what you are doing and when you see that message?

**Comment by davidpdrsn** [comment]
I recorded a quick video https://dl.dropboxusercontent.com/u/2155997/Magit%20commit%20not%20working.mov

**Comment by justbur** [comment]
Hm, ok thanks. After the popup appears what does `C-h v evil-state RET` say
the value of `evil-state` is? It should be 'emacs'

**Comment by davidpdrsn** [comment]
It said 'motion'.

I played around my init.el file and after removing the line

```elisp
(setq evil-motion-state-modes (append evil-emacs-state-modes evil-motion-state-modes))
```

it works.

Not quite sure what that line does, but I appreciate your help a lot :smile:

**Comment by justbur** [comment]
Yep that would have screwed it up. The evil-state used in the magit buffers
is important for evil-magit, so changing them will have unintended effects
like this. c is undefined in the motion state map. In emacs state, c just
inserts the character, which is what the magit popups are expecting you to
do.

**Comment by davidpdrsn** [comment]
Okay I see. Thanks for your help!
