### ISSUE TITLE
Previously set keys are re-bound

### ISSUE THREAD

**Issue by justmytwospence** [justbur/evil-magit#13]
In my evil configuration, I've set `C-b` to nil in `evil-motion-state-map`, because I like to use `C-b` as a prefix key. This is reset by evil-magit however, and attempting to re-bind to nil after loading evil-magit doesn't seem to do anything.

**Comment by justbur** [comment]
Hm that doesn't seem right. I don't do anything with `C-b`. Are you talking
about all buffers or just magit ones?

**Comment by justbur** [comment]
Well I lied. I do have a `C-b` binding. It would still help to know what buffers the problem is in.

**Comment by justbur** [comment]
This should fix it
```elisp
(evil-define-key evil-magit-state magit-mode-map "\C-b" nil)
```

**Comment by justmytwospence** [comment]
Sure does!
