### ISSUE TITLE
evil-magit disables M-x.

### ISSUE THREAD

**Issue by Alexander-Miller** [justbur/evil-magit#15]
To reproduce:
 * start `emacs -q`
 * load packages (el-get in my case)
 * activate `evil-mode`
 * run `evil-magit-init`
 * run `magit-status`
 * `M-x` will now be undefined

The binding can still be partially reintroduced by readding it to all of magit's mode-maps,
but that 1) should not be necessary in the first place, and 2) not even sufficient. In magit's
status buffer there is a single line which separates the Untracked Files and Unstaged Changes
sections. I've been unable to readd an `M-x` binding to that line no matter what I tried.
`global-set-key`, `(evil)-define-key` on any and all keymaps I could get my hands on did nothing
for that specific case.

Here's the exact list of keymaps I tried:

    (list
     evil-normal-state-map
     evil-visual-state-map
     evil-insert-state-map
     evil-motion-state-map
     magit-mode-map
     magit-status-mode-map
     magit-log-mode-map
     magit-diff-mode-map
     magit-branch-section-map
     magit-untracked-section-map
     magit-file-section-map
     magit-status-mode-map
     magit-hunk-section-map
     magit-stash-section-map
     magit-stashes-section-map
     magit-staged-section-map
     magit-unstaged-section-map))

I'm running the newest evil-magit pulled directly from github yesterday.
My magit version is 2.4.1-2-g7a4a760.

**Comment by justbur** [comment]
Sorry, stupid mistake. Should be fixed in https://github.com/justbur/evil-magit/commit/f10cd2c57a2bfcefdce3983bed717759442477b8

**Comment by Alexander-Miller** [comment]
The fix works :+1:
