### ISSUE TITLE
C-w

### ISSUE THREAD

**Issue by justmytwospence** [justbur/evil-magit#16]
When `evil-want-C-w-delete` is set to nil, Evil uses C-w for window switching keys (like Vim obviously). There is another evil setting, `evil-want-C-w-in-emacs-state`, that adds the C-w window switching even to emacs-state.  Evil-magit should probably respect one of these settings and remap magit-copy-selection-value to something else so that people have a way to switch out of the Magit windows.

**Comment by justbur** [comment]
Good point. Instead of checking those variables, I decided to put the binding in if `evil-magit-use-y-for-yank` is non nil, because in that case `C-w` is redundant. I could add an explicit option, but I think the functionality of `C-w` is useful in magit if it's not available under another command.

**Comment by justmytwospence** [comment]
:+1:
