### ISSUE TITLE
Option to easily scroll horizontally 

### ISSUE THREAD

**Issue by nixmaniack** [justbur/evil-magit#17]
If you have vertical split with magit and the changes you see don't fit in the window(commit window alongside changes) it becomes difficult to scroll horizontally without vim like bindings. We have to use arrow keys to scroll. 

Any options/suggestions?

**Comment by justbur** [comment]
Any idea what the preferred way to do this in magit is?

**Comment by nixmaniack** [comment]
I don't know of magit way per se, but in emacs since keybindings `C-[fbea]` are available it's easy to navigate around. You can use `C-x [<>]` to scoll left/right.

**Comment by justbur** [comment]
`C-f` for me is the gitflow popup. 

I added `C-t` to toggle text-mode a little while ago, which is one option.

I guess enough people have asked for this that it's time to explore what it would require. Moving `h` for help to `H` looks like it would work. There are two log popups on `l` and `L` and it looks reasonable to move them "up" to `L` and `C-l`. Would that be adequate?

**Comment by justbur** [comment]
Done in https://github.com/justbur/evil-magit/commit/99019a5c1529045b8e88dfe50ae8ccf3ed905362

Set `evil-magit-want-horizontal-movement` to `t`. I think I hit all of the points where something should change, but please let me know if you notice an inconsistency.

**Comment by nixmaniack** [comment]
> Moving h for help to H looks like it would work. There are two log popups on l and L and it looks reasonable to move them "up" to L and C-l. Would that be adequate?

Sure this is very much consistent with vim.

**Comment by nixmaniack** [comment]
Oh wow! That was quick. I will and and report any issues if found. Thanks!

**Comment by nixmaniack** [comment]
Works perfect. Thank you.
