### ISSUE TITLE
Add binding for magit-reset-popup

### ISSUE THREAD

**Issue by fbergroth** [justbur/evil-magit#19]
It was recently introduced.

**Comment by justbur** [comment]
Any suggestions for where to put it?

**Comment by fbergroth** [comment]
`X` feels natural, but I don't have a good suggestion that doesn't collide :confused:

**Comment by justbur** [comment]
`X` is taken already `k` and `K` were moved to `x` and `X`. Any other suggestions would be welcome.

**Comment by fbergroth** [comment]
For symmetry with `C-r` (`magit-reset`), I guess it makes sense to bind it to `C-R` or `M-r`.

Magit has `magit-reset` on `x` and `magit-reset-popup` on `X`.

**Comment by justbur** [comment]
Yes that would be the natural thing to do but I feel there must be a better way.

**Comment by justbur** [comment]
Here's some possibilities
 1. `C-R` because it follows the other rules. Bad because it's three keys and not very vim-like
 2. `'` for reset and `"` for the popup. Not mnemonic at all, but on the home row and not taken really.
 3.`,` for reset and `<` for the popup. I like the back arrow for reset, but that's about it. 

Do you like any of those?

**Comment by justbur** [comment]
I never liked `o` and `O` for revert, so maybe those are better for reset and we can put revert somewhere else. The mnemonic was "old", and maybe that's better for reset as in go back to an old state.

**Comment by andschwa** [comment]
Unfortunately the choice of `-` is also already taken, by `magit-diff-less-context`.

**Comment by justbur** [comment]
Crap, you're right. I forgot about that one, because I never use it. 

It seems that `=` would work for diff-less-context. Would that be adequate?

**Comment by andschwa** [comment]
Seems fine to me :)

**Comment by justbur** [comment]
@andschwa  Should be fixed now. Sorry for the oversight

**Comment by andschwa** [comment]
No problem :smile:
