### ISSUE TITLE
'=' not bound to magit-diff-less-context

### ISSUE THREAD

**Issue by marktran** [justbur/evil-magit#21]
I'm running `magit-20160410.222` with `evil-magit-20160324.1838` and noticed that `=` is bound to `magit-log-toggle-commit-limit` and isn't working correctly. Using `=` on a diff gives me this error: `Wrong type argument: consp, nil`.

`+` is bound to `magit-diff-more-context` and works fine.

**Comment by justbur** [comment]
Yep, you're right. This is a bug, but it's coming from a deficiency in evil IMO. I submitted a change [here](https://bitbucket.org/lyro/evil/pull-requests/59/evil-coreel-add-ignore-parent-option-to/diff) which will allow me to fix this easily. Thanks for the report.

**Comment by justbur** [comment]
@marktran the fix was merged into evil, but evil hasn't been updated on melpa yet so I'll wait a little to merge the evil-magit fix.

**Comment by justbur** [comment]
Got delayed because it took a while for evil to update. You'll need to update evil when you update this package and everything should work. It will take a few hours for this to be on Melpa

**Comment by marktran** [comment]
Just updated and looks like it's working. Thanks Justin!
