### ISSUE TITLE
Request for binding magit-stgit-popup

### ISSUE THREAD

**Issue by ratheesh** [justbur/evil-magit#22]
can you please introduce binding for `magit-stgit-popup` ?

**Comment by justbur** [comment]
What's the default binding for it?

**Comment by ratheesh** [comment]
Default magit binds `magit-stgit-popup` to `/`. But this is used for searching in evil mode.

**Comment by justbur** [comment]
stgit doesn't appear to be a part of default magit. Why not just rebind it
yourself in `magit-mode-map`?

**Comment by ratheesh** [comment]
okay. Thanks.
