### ISSUE TITLE
magit-gh-pulls help text needs to be overriden

### ISSUE THREAD

**Issue by robbyoconnor** [justbur/evil-magit#24]
There needs to be a way to override the helpdesk displayed in the magit-status buffer. Since <kbd>#</kbd> <kbd>g</kbd> is overriden, users will get confused when it doesn't work. My emacs lisp chops aren't great but will take a stab at this.

**Comment by justbur** [comment]
That text looks hard to change. I just removed the change in key binding

**Comment by robbyoconnor** [comment]
Will this cause problems with evil?

**Comment by justbur** [comment]
No it was just for consistency

**Comment by robbyoconnor** [comment]
Okay thanks @justbur =)

**Comment by d12frosted** [comment]
https://github.com/sigma/magit-gh-pulls/pull/95

**Comment by d12frosted** [comment]
Yesterday I made a PR for this https://github.com/sigma/magit-gh-pulls/pull/95. Was waiting for this to be accepted and then was gonna PR here 😸 

**Update** But to be honest, I like `# g` much more 😸 Though it's funny to listen to me, cause I don't do evil myself! 💃
