### ISSUE TITLE
Region Staging doesn't work

### ISSUE THREAD

**Issue by CestDiego** [justbur/evil-magit#4]
To reproduce: go into visual selection either with `v` or `V` in the magit-status buffer, inside a chunk... then try to move either up or down with `j` or `k`...the selection will dissapear.

**Comment by justbur** [comment]
It's working for me. I wonder if you just can't see the region because of your theme.

**Comment by CestDiego** [comment]
No, I try to `select` and then stage and it stages the whole chunk instead of some region of it.

**Comment by justbur** [comment]
Yes, I understand. It works for me. I can stage part of a chunk. I'll need more information to diagnose this.

What does `C-h k v` say in a chunk? What about `C-h j`? Should be `set-mark-command` and `evil-next-visual-line` respectively.

**Comment by CestDiego** [comment]
I figured this out. It's got to do with me having evil-escape-sequence at `jk`...everything is bound to what it needs but it seems evil-escape is doing some stuff that blocks `j` or `k`...

**Comment by CestDiego** [comment]
Must be related to https://github.com/syl20bnr/evil-escape/issues/52

**Comment by justbur** [comment]
Ah ok. Maybe file an issue with evil-escape. I haven't used evil-escape in
a while so I didn't test against it.

**Comment by justbur** [comment]
Noted in the readme so I'm going to close this for now. Please reopen if something changes

**Comment by CestDiego** [comment]
thanks :)
