### ISSUE TITLE
Doesn't take any effect

### ISSUE THREAD

**Issue by justmytwospence** [justbur/evil-magit#5]
This package isn't having any effect on my keybindings. Is it something wrong in my config?

```
(use-package magit
  :commands
  (magit-blame-mode
   magit-commit
   magit-diff
   magit-log
   magit-status)
  :init
  (with-eval-after-load 'evil-leader
    (evil-leader/set-key
      (kbd "gb") #'magit-blame
      (kbd "gc") #'magit-commit
      (kbd "gd") #'magit-diff
      (kbd "gl") #'magit-log
      (kbd "gr") #'magit-reflog
      (kbd "gs") #'magit-status))
  (with-eval-after-load 'which-key
    (which-key-declare-prefixes
      "<SPC>g" "Git"))
  :config
  (add-hook 'magit-diff-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-log-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-log-select-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-refs-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-revision-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-status-mode-hook #'hl-line-mode)
  (add-hook 'magit-status-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'with-editor-mode-hook 'evil-insert-state)
  (bind-keys
   :map magit-status-mode-map
   ("<C-tab>"   . nil)
   ("<backtab>" . magit-section-cycle))
  (set-face-background 'magit-diff-added-highlight "SeaGreen4")
  (set-face-background 'magit-diff-removed-highlight "IndianRed4")
  (setq magit-completing-read-function 'magit-ido-completing-read)
  (setq magit-push-always-verify nil)
  (use-package magit-gh-pulls
    :config
    (add-hook 'magit-mode-hook #'turn-on-magit-gh-pulls)))

(require 'evil-magit)
```

**Comment by justbur** [comment]
Looks like you are loading it too early. You want to load it after magit is loaded. Try this
```elisp
(use-package magit
  :commands
  (magit-blame-mode
   magit-commit
   magit-diff
   magit-log
   magit-status)
  :init
  (with-eval-after-load 'evil-leader
    (evil-leader/set-key
      (kbd "gb") #'magit-blame
      (kbd "gc") #'magit-commit
      (kbd "gd") #'magit-diff
      (kbd "gl") #'magit-log
      (kbd "gr") #'magit-reflog
      (kbd "gs") #'magit-status))
  (with-eval-after-load 'which-key
    (which-key-declare-prefixes
      "<SPC>g" "Git"))
  :config
  (require 'evil-magit)
  (add-hook 'magit-diff-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-log-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-log-select-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-refs-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-revision-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'magit-status-mode-hook #'hl-line-mode)
  (add-hook 'magit-status-mode-hook (lambda () (setq cursor-type nil)))
  (add-hook 'with-editor-mode-hook 'evil-insert-state)
  (bind-keys
   :map magit-status-mode-map
   ("<C-tab>"   . nil)
   ("<backtab>" . magit-section-cycle))
  (set-face-background 'magit-diff-added-highlight "SeaGreen4")
  (set-face-background 'magit-diff-removed-highlight "IndianRed4")
  (setq magit-completing-read-function 'magit-ido-completing-read)
  (setq magit-push-always-verify nil)
  (use-package magit-gh-pulls
    :config
    (add-hook 'magit-mode-hook #'turn-on-magit-gh-pulls)))


```

**Comment by justmytwospence** [comment]
I should have mentioned that your suggestion was actually the first thing I tried. It seems that no matter where I move the require statement, none of the keybindings get overridden.

**Comment by justbur** [comment]
How are you loading evil?

**Comment by justmytwospence** [comment]
Ah its probably because I use evil-local-mode and not the global mode.

**Comment by justbur** [comment]
Could be. This package assumes evil-local-mode is used in magit buffers
(and git-rebase-mode ones)

**Comment by justmytwospence** [comment]
Yep, this works:

```
(use-package evil-magit
    :config
    (add-hook 'magit-mode-hook 'evil-local-mode))
```

Maybe evil-local-mode should be automatically turned on by this package if global evil mode is not on but evil is installed?

**Comment by justbur** [comment]
Possibly. Certainly worth making a note of it in the readme.

You probably want to use the git-rebase-mode-hook also

**Comment by vyp** [comment]
Off topic but use-package now has an after keyword so you don't need nested `use-package`: https://github.com/jwiegley/use-package/pull/276 (although of course it doesn't make a difference)

**Comment by justmytwospence** [comment]
Thanks @justbur & @vyp

**Comment by justbur** [comment]
Added a note to the readme. I might add an option to add the right hooks automatically at some point if it's still something that comes up 

Thanks for the report

**Comment by decoursin** [comment]
I have (evil-mode 1), yet I was having the same problem as @justmytwospence. It didn't work for me until I added: 

```
(add-hook 'magit-mode-hook 'evil-local-mode)
(add-hook 'git-rebase-mode-hook 'evil-local-mode)
```

Thanks so much!

**Comment by justbur** [comment]
@decoursin that shouldn't be necessary. What order are you loading evil magit and this package in?

**Comment by decoursin** [comment]
I confirm that when I comment these lines out, it stops working. Loading goes like this: evil -> (evil-mode 1) -> magit -> evil-magit. Also, I started emacs fresh then eval-ed "(evil-mode 1)", and it still didn't work.

**Comment by justbur** [comment]
Latest versions of everything?

**Comment by decoursin** [comment]
Well, I don't know for sure if I have the latest version of *everything* but pretty close. I'm on emacs 24.5, I reinstalled all my packages just a couple weeks ago, and I reinstalled magit and evil-magit like just yesterday trying to get this working.

**Comment by justbur** [comment]
@decoursin so (evil-mode 1) basically just enables evil-local-mode in each buffer. That's why your fix shouldn't be necessary. There could be something in your config that is changing this which may be why it works for you. It's just hard for me to say without more info. What you said of the loading order seems perfectly fine to me. If you enable evil after opening a magit buffer there could be a one time issue, but that's all that comes to mind. 

Sorry no back ticks on my phone but this should work after emacs -Q

(require 'evil)
(evil-mode 1)
(require 'magit)
(require 'evil-magit)

Actually the exact position of (evil-mode 1) shouldn't matter as long as it comes before you open a new magit buffer.

**Comment by decoursin** [comment]
Yeah, that's the order in which I'm loading things. Here, if you want, take a look at [my emacs](https://github.com/decoursin/emacs.d) which the latest one that I'm using right now. Honestly, this fix is fine for me because it works, so only delve into my emacs if you wish, as it's kind of messy anyways.

**Comment by justbur** [comment]
I think I see the problem. You're setting the evil initial state for the
magit buffers. Evil-magit picks an initial state too which is motion by
default. You can configure this with evil-magit-state. Just be aware that
the keybindings here are state dependent so you can either let evil-magit
set up the defaults for you or your config needs to be consistent with what
evil-magit is doing.

Try letting evil-magit manage the states first and then tweak after that if
you need to.

I just flipped through your config but that seems to be the problem. Hope
that makes enough sense.

**Comment by decoursin** [comment]
Hmm I think you were talking about this in my [init-evil.el file](https://github.com/decoursin/emacs.d/blob/master/lisp/init-evil.el), which I commented out:
```
;; (magit-mode . normal)
;; (magit-popup-mode . normal)
;; (magit-branch-manager-mode . emacs)
```
I also had init-git.el file which referenced magit, and I commented out those lines. Now, pretty much the only references to magit are in init-magit.el. Still not working though.

**Comment by justbur** [comment]
@decoursin that's what I was referring to yes. if that doesn't work then I don't know what to tell you. My guess is that it's something odd in your config somewhere. If you can give me some Sumple repro steps i can investigate further.
