### ISSUE TITLE
`o` for revert?

### ISSUE THREAD

**Issue by justmytwospence** [justbur/evil-magit#6]
Whats the rationale for using `o` for revert? `o` is not really mnemonic for revert and because it is normally used for submodules, it forces us to rebind submodules to `>` as well.  I propose that `o` be set back to submodules, and use something else for revert like `<`, which is more evocative of revert than `>` is for submodules (imho at least).

**Comment by justbur** [comment]
That's probably the worst one, so yes I agree. It was meant to be for old, but it's a stretch. The issue with `<` is that there's a `v` and a `V`, so what would the corresponding caps version be? I'm open to suggestions on this one. I tried `C-o` for submodules but that wasn't working in the popup for some reason.

I'm happy to make changes, but I'm not sure your proposal is the right one.

**Comment by justmytwospence** [comment]
Now that you give me the "old" mnemonic I could live with it. I'll keep thinking for alternatives though.

**Comment by justbur** [comment]
ok, like I said I don't like it, but that was the best I came up with

**Comment by justbur** [comment]
Using `<` for revert would work if you can afford to lose quick access to the revert popup. Default magit is to have `v` revert and `V` for the revert popup, but I could make `<` revert and `h<` be the revert popup (main popup then revert key). Does that make sense?

**Comment by justbur** [comment]
and put the submodule key back, although I don't know the connection between `o` and a submodule

**Comment by justbur** [comment]
@justmytwospence another option would be restoring `v` for revert, keeping `V` for linewise selection, and restoring `o` for submodules?
