### ISSUE TITLE
Conflicts with magit-gh-pulls

### ISSUE THREAD

**Issue by justmytwospence** [justbur/evil-magit#7]
`evil-search-word-backward` conflicts with the `#` prefix that magit-gh-pulls uses. I have no idea why evil binds `#` to this command, I don't think thats what vim does. Can anyone replicate this to be sure?

**Comment by justbur** [comment]
I'm only doing minimal stuff for magit-gh-pulls at the moment, mostly because I don't use it. Can you try this and see if it resolves your issues?
```elisp
  (evil-make-overriding-map magit-gh-pulls-mode-map evil-magit-state)
```

**Comment by justbur** [comment]
after loading evil-magit that it

**Comment by justbur** [comment]
@justmytwospence Did you get a chance to try the suggestion?

**Comment by justbur** [comment]
I added the suggested fix. Let me know if you have a problem with it
